spring:
  datasource:   #\u6570\u636E\u6E90\u914D\u7F6E
    type: com.alibaba.druid.pool.DruidDataSource #\u8FDE\u63A5\u6C60\u7C7B\u578B
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver #\u6570\u636E\u5E93\u9A71\u52A8\u7A0B\u5E8F\u7C7B
    url: jdbc:mysql://localhost:3306/blog?serverTimezone = Asia/Shanghai
    #RabbitMq配置
  rabbitmq:
    host: 192.168.180.130
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  redis:
    host: 192.168.180.130
    port: 6379
    #jpa:
    # hibernate:
    # ddl-auto: update
    #show-sql: true


  jpa:
    hibernate:
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  PhysicalNamingStrategyStandardImpl:#mybatis\u7684\u914D\u7F6E\u5982\u4E0B
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.gjy.boke.entity

logging:
  level:
    root: info
    com.gjy.boke: debug
  file:
    name: log/blog-dev.log
server:
  port: 8081
